import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div>
          <header className="w-full p-6 flex justify-between items-center bg-white text-black">
            <nav>
              <ul className="flex space-x-4">
                <a href="/" className="hover:underline">Home</a>
                <li><a href="#experience" className="hover:underline">Experience</a></li>
                <li><a href="/projects" className="hover:underline">Projects</a></li>
                <li><a href="#contact" className="hover:underline">Contact</a></li>
              </ul>
            </nav>
            <div className="flex space-x-4">
              <a href="#"><img src="/linkedin.png" alt="LinkedIn" width={35} /></a>
              <a href="#"><img src="/github.png" alt="GitHub" width={35} /></a>
            </div>
          </header>

          <main>{children}</main>

          <footer className="py-4 text-center">
            <p>© 2024 Bara Portfolio</p>
          </footer>
        </div>
      </body>
    </html>
  );
}

